### ISSUE TITLE
Some small details

### ISSUE THREAD

**Issue by PierreClementCazon** [michielStaes/grav-theme-phantom#7]
Hi,

The title of the article is not displayed in the right place on the home page and the beginning of the article is not displayed at all : 

![capture](https://user-images.githubusercontent.com/36991574/38832221-2b374920-41c2-11e8-8119-fb76a6802ee4.PNG)

The title of the page does not have the H1 tag either on the home page or on an article : 

![capture2](https://user-images.githubusercontent.com/36991574/38832224-2e72b3ae-41c2-11e8-90d1-5466cee37162.PNG)

How to delete labels as on the original version ?

![capture3](https://user-images.githubusercontent.com/36991574/38832228-314bedd4-41c2-11e8-8ced-bc904485b544.PNG)

Thank you in advance for your help and thank you again for responding to my request so quickly.

**Comment by michielStaes** [comment]
Hi Pierre, 
- How are you adding content? In the admin page you can clearly add H1 tags to your content.
(on each page)

- I'm not sure what you mean by '**How to delete labels as on the original version ?**'

- '**The title of the article is not displayed in the right place on the home page and the beginning of the article is not displayed at al**l'  This would suprise me, but I will look into it tonight.


Michiel

**Comment by PierreClementCazon** [comment]
Hi,

- Ideally, the title of the page should be included in an H1 tag (while keeping the current style): https://www.pierreclementcazon.pro/test
- On the demo of the theme, there is no label: https://html5up.net/phantom
- Currently, the page title is displayed instead of the beginning of the article : https://www.pierreclementcazon.pro/

Hoping to have been clear with my approximate English... sorry!

**Comment by PierreClementCazon** [comment]
@michielStaes, I'm available if you need more information !
